[project]
name = "personal-premis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "frozen-flask>=1.0.2",
    "markdown>=3.10",
    "pandas>=2.3.3",
    "pydash>=8.0.5",
    "rdflib>=7.4.0",
]
